name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Mod
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@v3
        with:
          sdk: v3.0.0
